# Homework 1
Due by 9/14/15 at 11:59pm EST

-----------

## Introduction

Some notes here perhaps...

In [6]:
# special IPython command to prepare the notebook for matplotlib
%matplotlib inline 

import math as m
import scipy.stats as ss
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import Image

## Problem 1

#### Problem 1a 
Generate a random data set with 100 rows and 4 columns (A, B, C, D) defined as:
- A = Normal distribution with mean = 5, variance = 3
- B = Uniform distribution 5 to 7
- C = A+B
- D = A\*B

Generate the data by row using a random seed 123456789.


In [41]:
## generate data by using the seed 123456789
np.random.seed(123456789)

A = np.random.normal(5,m.sqrt(3),100) # Genrate A which is a normal dist list of mean 5, var 3, size 100
B = np.random.uniform(5,7,100) # Genrate B which is an uniform dist between 5 to 7, size 100
C = A + B # Generat C which is the sum of A and B
D = A * B # Generat D which is the product of A and B


[ 5.49529161  5.84290871  5.0733133   6.44796539  6.06642627  5.6267727
  6.5821647   5.6740692   6.6665014   6.36307727  5.31825019  5.32101949
  5.9645844   6.28169957  6.02066806  5.65260359  5.34561097  6.30529469
  6.44910338  6.33466618  6.16654905  5.52626429  5.34467364  5.99856977
  5.00900118  6.49039109  5.3004384   6.02497614  6.83379297  6.0381566
  6.27379309  5.59361636  6.87390776  5.1185544   5.85106268  6.90251711
  5.76032628  5.56863869  5.53602517  5.13240892  6.28317914  6.45187187
  6.43080204  6.7400199   5.68541663  6.94699995  6.71849824  5.37310302
  5.89766234  5.04967045  5.86403147  5.57455204  5.40475448  5.10668658
  5.62575794  5.45047517  5.84294418  5.49050103  6.53441102  5.71577812
  5.74719917  6.40562504  5.61383588  5.63572852  5.7176873   5.16855753
  6.72340855  5.20741382  5.95106996  5.18443235  6.45315731  5.13264512
  5.00867605  5.76050096  5.26191359  6.33050247  5.83515666  5.37846458
  5.53740453  5.3795532   6.42054656  6.29581803  5.2

#### Problem 1b
Compute the correlation coefficient and sample covariance between the 4 variables.  That is, write the actual loop rather than call the correlation or covariance functions. Then print these matrices. Is either matrix symmetric? 

In [70]:
temp = [A,B,C,D] # Create temp list to hold 4 columns

tempName = ['A','B','C','D'] # Create tempName list to hold the 4 columns names
    
for i in range(len(temp)): # Pick the first var looping through the temp list 
    
    for j in range(len(temp)): # Pick the second  var looping through the temp list
        
        if i!= j: # If the two vars are not the same
            
            # Print out the correlation coefficient and covariances between the two vars
            # TO-DO !! Need to print out if symmetric or not
            print ('Coef of %s and %s \n' % (tempName[i],tempName[j]),np.corrcoef(temp[i],temp[j]),'\n')
            print ('Covar of %s and %s \n' % (tempName[i],tempName[j]),np.cov(temp[i],temp[j]),'\n')


Coef of A and B 
 [[ 1.          0.12296092]
 [ 0.12296092  1.        ]] 

Covar of A and B 
 [[ 2.73496624  0.11064043]
 [ 0.11064043  0.29603393]] 

Coef of A and C 
 [[ 1.          0.95412407]
 [ 0.95412407  1.        ]] 

Covar of A and C 
 [[ 2.73496624  2.84560667]
 [ 2.84560667  3.25228102]] 

Coef of A and D 
 [[ 1.          0.95674997]
 [ 0.95674997  1.        ]] 

Covar of A and D 
 [[   2.73496624   16.53103805]
 [  16.53103805  109.15694407]] 

Coef of B and A 
 [[ 1.          0.12296092]
 [ 0.12296092  1.        ]] 

Covar of B and A 
 [[ 0.29603393  0.11064043]
 [ 0.11064043  2.73496624]] 

Coef of B and C 
 [[ 1.          0.41445942]
 [ 0.41445942  1.        ]] 

Covar of B and C 
 [[ 0.29603393  0.40667436]
 [ 0.40667436  3.25228102]] 

Coef of B and D 
 [[ 1.          0.39465887]
 [ 0.39465887  1.        ]] 

Covar of B and D 
 [[   0.29603393    2.24345984]
 [   2.24345984  109.15694407]] 

Coef of C and A 
 [[ 1.          0.95412407]
 [ 0.95412407  1.        ]] 

Cov

## Problem 2

####Problem 2a
Draw 30 samples from a Poisson distribution with lambda = 7  using random seed 123456789.

In [12]:
np.random.seed(123456789) # generate data by using the seed 123456789

posonRand = np.random.poisson(7,30) # Genrate posonRand which is a poisson dist list of lam 7, size 30


#### Problem 2b
Define two functions to compute the mean and median.  That is, do not call the mean or median function, but write the code.  

In [9]:
"""
Function
--------
Mean

Return an integer that is the computed
arithmetic mean of the input array

Parameters
----------
values : array[int]
    The array of values

Returns
-------
an int
   an integer that is the computed 
   arithmetic mean

Example
-------
>>> mean([1,2,3,4,5])
"""

def mean(array): # Declare function called mean, taking input array
    
    res = np.mean(array) # Compute the arithmetic mean of the array
    
    return res # Return the result


    

In [14]:
"""
Function
--------
Median

Return an integer that is the computed
arithmetic median of the input array

Parameters
----------
values : array[int]
    The array of values

Returns
-------
an int
   an integer that is the computed 
   arithmetic median

Example
-------
>>> median([1,2,3,4,5])
"""

def median(array): # Declare function called mean, taking input array
    
    res = np.median(array) # Compute the arithmetic mean of the array
    
    return res # Return the result



####Problem 2c
Use the functions you just defined to calculate the mean and median of the samples collected in problem 2a.  Is the distribution of values skewed left, right, or neither? Is it skewed positive, negative, or neither?

In [15]:

print ('Mean of samples in problem 2a is %.2f' % mean(posonRand)) #Print the mean of samples in 2a

print('Median of samples in problem 2a is %s' % median(posonRand)) #Print the median of samples in 2a

### The distribution skews right, and it is skewed negative.

Mean of samples in problem 2a is 6.53
Median of samples in problem 2a is 6.5


## Problem 3
Over the course of a two week period, my mailman delivered [5, 3, 4, 3, 6, 7, 2, 2, 3] pieces of mail each weekday.  On the last Friday, I received no mail.  My theory is that he took the day off.  

####Problem 3a
Assuming a normal distribution from the first 9 days, what is the probability of receiving no mail on that last Friday?   (Don’t overthink this problem)  

In [20]:
m = mean([5, 3, 4, 3, 6, 7, 2, 2, 3]) # mean of the mail delivery of 9 days

std = np.std([5, 3, 4, 3, 6, 7, 2, 2, 3])  # stand deviation of the mail delivery of 9 days

# Use scipy.stats module to compute the probability at 0 given the normal distribution
print (' The probability of receiving no mail on last Friday is %f' % ss.norm(m,std).pdf(0)) 



 The probability of receiving no mail on last Friday is 0.015578


#### Problem 3b
Are there any issues with using a normal distribution for this problem?

**Response:**

In [ ]:
## There are several issues using normal distributions for this problem

## Problem 4
Alzheimer’s Disease is a terrible affliction affecting 5.3 million of the 319 million people in this country and is the only top-10 cause of death in this country that cannot be prevented, cured, or slowed (www.alz.org/facts).   Researchers have developed a new method for predicting Alzheimer’s, but like most medical tests, it is not perfect.  

If a patient has Alzheimer’s there is a 75% chance of a positive prediction.  If they don’t have Alzheimer’s the chance of a positive prediction is 20%.   Compute the probability of having Alzheimer’s if the prediction is positive.  Show your work.

In [20]:
Prate = 5.3/319 # Prevalance rate = (TP+PN)/(TP+PN+FP+TN) Alzheimer's disease in population 

Specificity = 1 - 0.2 # Probability of a non-patient diagnosed as negative = TN/(FP+TN)

Sensitivity = 0.75 # Probability of an patient diagnosed as positive = TP(TP+FN)

Diseased = 100 # Suppose there are 100 diseased people

TP = Diseased * Sensitivity # There are 75 diseased people diagnosed as patient

NonDiseased = 100 / Prate # Nondiseased people will be huge in this case 6250 because it is a rare disease

FP = NonDiseased * (1- Specificity) # There are 1250 people who don't have disease but diagnosed as patient

PosPredictive = TP/(TP+FP) # Postive predicative rate is 0.0586

print ('The probability of having Alzheimer if prediction is postive is %.4f' % PosPredictive) # Print the result

The probability of having Alzheimer if prediction is postive is 0.0586


## Problem 5
Given the matrices below, compute (A + B’)\*C

<img src='hw1p5.png'>

In [7]:
A = np.matrix(((1,2),(3,4),(2,2))) # Matrix A

B = np.matrix(((3,2,3),(4,1,1))) # Matrix B

C = np.matrix(((1,2))).transpose() # Matrix C

B_T = B.transpose() # Tranpose Matrix B

print ((A+B_T)*C) # Print the computed (A + B’)*C

[[4 6]
 [5 5]
 [5 3]]
[[16]
 [15]
 [11]]


## Problem 6
The Monty Hall problem as discussed in lecture came from a popular game show—this is a variation since I recently learned the same problem was covered in the Data Science course.   The contestant is faced with a choice of **7** doors.  Behind **5** of the doors, there is a goat; a car lies behind the other **2** doors.  The contestant chooses one door but cannot look behind it.  The host opens two of the other doors.  The choice is whether the contestant should keep the initial choice or switch to one of the other closed doors.  Simulate this using python code over 1000 iterations.  Without loss of generality, you can assume that the contestant choice is always door A.  The position of the cars is random with each iteration.   Compute the chance of winning with each strategy:  keeping the initial choice, or switching doors.

In [5]:
import random

iterations = 1000 # 1000 iterations

doors = ["goat"] * 5 + ["car"] * 2 # The first unopen 7 doors with 5 goats, 2 cars

doors_after = ["goat"] * 3 + ["car"] * 2 # The 5 left unopen doors after Monty opens 2 goats door

change_wins = 0 # Counts of change wins

change_loses = 0 # Counts of change loese

stay_wins = 0 # Counts of stay wins

stay_loses = 0 # Counts of stay loses

for i in range(iterations): # Simulate in each of the iterations
    
    random.shuffle(doors) # Shuffle the 7 doors
    
    random.shuffle(doors_after) # Shuffle the 5 doors
    
    n = random.randrange(7) # Pick door n:
    
    m = random.randrange(5)  # If change door, pick door m
    
    if doors[n] == "car": # If the first pick n door has car
        
        change_loses += 1 # Then change loses
        
        stay_wins += 1 # Stay wins
        
    
    elif doors_after[m] == "car": # If change and the picked door m has car
        
        change_wins += 1 # Then change wins
        
        stay_loses += 1 # Then stay loses

        
    else: # Else if either door n or door m has cars
        
        change_loses += 1 # Then change loses
        
        stay_loses += 1 # Then stay also loses

print ("Changing has %s wins and %s losses" % (change_wins, change_loses)) # Print strategy of change results

print ("Staying has %s wins and %s losses" % (stay_wins, stay_loses)) # Print strategy of stay results

perc_c = (100.0 * change_wins) / (change_wins + change_loses) # Compute winning chance in strategy of change

print ("By changing you win %.3f of the time" % perc_c) # Print winning chance in strategy of change

perc_s = (100.0 * stay_wins) / (stay_wins + stay_loses) # Compute winning chance in strategy of stay

print ("By staying you win %.3f of the time" % perc_s)  # Print winning chance in strategy of stay

Changing has 294 wins and 706 losses
Staying has 268 wins and 732 losses
By changing you win 29.400 of the time
By staying you win 26.800 of the time
